new save feature
zhongyizh/hipond-serverless pull request #14
Opened 2024-06-21 05:29 UTC by yichenl61

2024-06-24 16:18 UTC, zhongyizh requested changes
See comments details

2024-06-24 16:18 UTC, zhongyizh commented on cloudfunctions/checkSaveStatus/index.js
> +		console.log("已收藏")
如果需要使用console.log，打出的信息需要意义更加明确

2024-06-24 16:18 UTC, zhongyizh commented on cloudfunctions/savePost/index.js
> +// 云函数入口文件
云函数的名称savePost可能有歧义

2024-06-24 16:18 UTC, zhongyizh commented on cloudfunctions/savePost/index.js
> +			throw new Error("No record found, new document is going be added.")
感觉这里判空可能用if/else更好，try/catch有点影响可读性

2024-06-24 16:18 UTC, zhongyizh commented on pages/detail/detail.js
> +            "postData.saveCount": (this.data.postData.saveCount? this.data.postData.saveCount : 0)  + 1
当没有saveCount的时候会显示1？

2024-06-24 16:18 UTC, zhongyizh commented on cloudfunctions/checkSaveStatus/index.js
> +	const data = record.data[0].list
这里需要判空，因为会有用户在saveList集合里没有记录的情况

2024-06-24 16:18 UTC, zhongyizh commented on pages/tab-bar/mine/mine.js
> +		}).count()
格式需要和之前的代码尽量保持统一

2024-06-24 16:18 UTC, zhongyizh commented on pages/tab-bar/mine/mine.wxml
> +              <view  class="grid-box" bindtap="navigateToDetailSaved" data-index="{{index}}">
多了个空格
格式需要和之前的代码尽量保持统一

2024-06-24 19:26 UTC, IsaacYingqiMa commented on pages/tab-bar/mine/mine.js
> +		}).count()
现在有很多缩进都有点乱咱们可以确定一下缩进格式和长度

2024-06-24 19:27 UTC, IsaacYingqiMa commented on cloudfunctions/savePost/index.js
> +			throw new Error("No record found, new document is going be added.")
感觉统一就好

2024-06-26 19:35 UTC, zhongyizh submitted a review, later dismissed

2024-06-26 19:39 UTC, zhongyizh approved these changes, later dismissed
resolve conflict

2024-06-27 21:01 UTC, IsaacYingqiMa approved these changes
okkk

2024-06-27 21:01 UTC, merged