Feature/new post listing
zhongyizh/hipond-serverless pull request #23
Opened 2024-07-25 05:53 UTC by yichenl61

2024-07-25 14:30 UTC, zhongyizh requested changes
Need to resolve merge conflict

2024-07-25 14:30 UTC, zhongyizh commented on image/info-icon.png
图标需要使用SVG格式

2024-07-25 14:30 UTC, zhongyizh commented on pages/post/new-post-listing/new-post-listing.js
> +    subitButtonType: 'submit-button'
submit拼错了

2024-07-25 14:30 UTC, zhongyizh commented on pages/post/new-post-listing/new-post-listing.wxss
> +  width: 100%;
默认是100%，可以不用写这个属性

2024-07-25 14:30 UTC, zhongyizh commented on cloudfunctions/newUserCheck/index.js
> +    if (userData.oldUser === undefined) {
bool类型的属性名使用类似 isOldUser 可读性更好

2024-07-25 14:30 UTC, zhongyizh commented on pages/post/new-post-listing/new-post-listing.js
> +        if(!res.camcle){
typo?

2024-07-25 14:30 UTC, zhongyizh commented on pages/post/new-post-listing/new-post-listing.js
> +    // this.updateButtonStatus();
去掉不用的代码

2024-07-25 14:30 UTC, zhongyizh commented on pages/post/new-post-listing/new-post-listing.js
> +    showMultiTextAndTitle: false,
变量名/属性名需要更好地反应它的作用

2024-07-25 16:15 UTC, zhongyizh submitted a review, later dismissed

2024-07-25 16:22 UTC, zhongyizh commented on pages/post/new-post-listing/new-post-listing.wxml
>  	<!-- TODO: 需要upload这个区域能横向滚动，而不是整个页面都能滚动 -->
好像改好了？确认一下没问题就把TODO去掉吧

2024-07-26 02:50 UTC, yichenl61 commented on cloudfunctions/newUserCheck/index.js
> +    if (userData.oldUser === undefined) {
这个要改数据库先不改了吧

2024-07-26 03:00 UTC, closed without merging